---
- name: Load kernel modules required for Neutron
  include: modules.yml

- name: Set sysctl variables for Neutron
  sysctl:
    state: present
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  with_dict: "{{ neutron_sysctl }}"

- name: Set DNS resolvers if unset
  lineinfile:
    state: present
    dest: /etc/resolv.conf
    create: yes
    line: "nameserver {{ item }}"
  with_items: "{{ default_resolvers }}"
  when: ansible_dns.nameservers is undefined

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: networking.yml
