---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- modprobe:
    state: present
    name: "{{ item }}"
  with_items: "{{ neutron_modules }}"
