---
- name: Create required OVS bridges
  openvswitch_bridge:
    bridge: "{{ item }}"
    state: present
  with_items:
    - br-ext
    - br-vlan

- name: Set br-ext external bridge ID
  openvswitch_bridge:
    bridge: br-ext
    state: present
    external_ids:
      bridge-id: br-ext
