---
- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  service:
    state: stopped
    name: firewalld
    enabled: no
  ignore_errors: True

- name: Installing iptables-services
  yum:
    name: iptables-services
    state: present

- name: Assemble list of ifcfg scripts
  find:
    path: /etc/sysconfig/network-scripts
    recurse: yes
    patterns: ifcfg-*
    use_regex: True
  register: ifcfg_files

- name: Remove interfaces from NetworkManager's control
  lineinfile:
    state: present
    line: NM_CONTROLLED=no
    regexp: ^NM_CONTROLLED
    dest: "{{ item }}"
  with_items: "{{ ifcfg_files.files|map(attribute='path')|list }}"
  when: ifcfg_files is defined

- name: Disable NetworkManager
  service:
    state: stopped
    name: NetworkManager
    enabled: no
  ignore_errors: True

- name: Add Platform9 Yum repository
  yum:
    name: https://s3-us-west-1.amazonaws.com/platform9-neutron/noarch/platform9-neutron-repo-1-0.noarch.rpm
    state: present
    update_cache: yes

- name: Install Open vSwitch
  yum:
    name: openvswitch
    state: present
    disablerepo: '*'
    enablerepo: 'platform9-neutron-el7-repo'

- name: Enable and start Open vSwitch
  service:
    name: openvswitch
    state: started
    enabled: yes
