---
##########################################################################################################
## network_hook:
##
## This hook is a user-defined script for site-specific network configurations.
## Feel free to modify as needed for your environment.
##########################################################################################################

##
## By default, pf9-express creates an interface named "bond0" and adds it to an OVS bridge named "br-pf9".
##
- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
