- name: Create pf9 installers directory
  connection: local
  file:
    path: "files/{{ du_host }}"
    state: directory

- name: Download Platform9 installers
  connection: local
  get_url:
    url: "{{ du_url }}/private/platform9-install-{{ item }}.sh"
    dest: "files/{{ du_host }}/platform9-install-{{ item }}.sh"
    headers: "X-Auth-Token:{{ hostvars['localhost']['os_auth_token'] }}"
    validate_certs: no
  with_items:
    - debian
    - redhat
