---
- debug: var=bond_members
- debug: var=bond_sub_interfaces

- block:
  - name: "RedHat - attach physical interfaces to the bond"
    template:
      src: rhel-ifcfg-interface.j2
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{item}}"
      mode: 0644
    with_items: "{{bond_members}}"
  when: bond_members is defined
  register: bond_task_result

- block:
  - name: "RedHat - attach physical interfaces to the bond"
    template:
      src: rhel-ifcfg-sub-interface.j2
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{bond_ifname}}.{{item['vlanid']}}"
      mode: 0644
    with_items: "{{bond_sub_interfaces|list}}"
  when: bond_sub_interfaces is defined

- name: "Redhat - Reboot if there was a change"
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: bond_task_result is changed

- name: "Redhat - Wait for the reboot to complete if there was a change"
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: bond_task_result is changed
